version: "3.7"
networks:
 kong-net:
   driver: bridge
services:
#######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - "./kong-plugin:/usr/local/custom/kong/plugins/license-manager"
    networks:
      - kong-net
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_LUA_PACKAGE_PATH: /usr/local/custom/?.lua;;
      KONG_PLUGINS: bundled, license-manager
      KONG_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8002:8002"
  express-service:
    image: express-service:latest
    container_name: express-service
    build:
      context: ./express-app
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - kong-net
    ports:
      - "3000:3000"
  lm-service:
    image: lmagent:latest
    container_name: lm-service
    build:
      context: ./license-manager-app
      dockerfile: ./Dockerfile
    networks:
      - kong-net
    ports:
      - "5000:5000"