###
GET http://localhost:8001/services
Accept: "application/json"
###
GET http://localhost:8000/api/express/hello/
Accept: "application/json"

###

GET http://localhost:8000/api/express/redirect
Accept: "application/json"

###
POST http://localhost:5000/acquire
Accept: "application/json"